# Generated by Django 2.2.12 on 2020-06-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='myname',
        ),
    ]
